// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Arc1(lv_event_t * e);
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label2;
void ui_event_ImgButton10(lv_event_t * e);
extern lv_obj_t * ui_ImgButton10;
// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
void ui_event_ImgButton6(lv_event_t * e);
extern lv_obj_t * ui_ImgButton6;
extern lv_obj_t * ui_Label10;
// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
void ui_event_Spinner2(lv_event_t * e);
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui__temporary_image);
LV_IMG_DECLARE(ui_img_a_corn_poppy_png);    // assets/a corn poppy.png
LV_IMG_DECLARE(ui_img_a_corn_poppy_3_png);    // assets/a corn poppy_3.png
LV_IMG_DECLARE(ui_img_2960017);    // assets/3-arc.png
LV_IMG_DECLARE(ui_img_stby_png);    // assets/STBY.png
LV_IMG_DECLARE(ui_img_ready_png);    // assets/Ready.png
LV_IMG_DECLARE(ui_img_01_png);    // assets/01.png
LV_IMG_DECLARE(ui_img_02_png);    // assets/02.png
LV_IMG_DECLARE(ui_img_03_png);    // assets/03.png
LV_IMG_DECLARE(ui_img_04_png);    // assets/04.png
LV_IMG_DECLARE(ui_img_05_png);    // assets/05.png
LV_IMG_DECLARE(ui_img_06_png);    // assets/06.png
LV_IMG_DECLARE(ui_img_ready_01_png);    // assets/Ready_01.png
LV_IMG_DECLARE(ui_img_ready_02_png);    // assets/Ready_02.png
LV_IMG_DECLARE(ui_img_stby_01_png);    // assets/STBY_01.png
LV_IMG_DECLARE(ui_img_stby_02_png);    // assets/STBY_02.png



LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_Title);
LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_Number);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_Title);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
